kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
spec:
  type: NodePort
  selector:
    app: react-service
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31000

---

apiVersion: apps/v1
kind: Devs
metadata:
  labels:
    app: myWeb
  name: myWeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myWeb
  template:
    metadata:
      labels:
        app: myWeb
    containers:
      - name: myNginxWeb
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports: 
        - containerPort: 80